### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by Correct-Syntax** [t1m0thyj/berean#1]
Hi, this is a neat idea. This is along the lines of something I've been wanting to create myself for quite some time actually, so I think I'd like to help with this project. 😄 

I see the layout is quite similar to e-sword. Do you have plans for custom (and modern) layout and look? If so, I think I could help with that as I have experience with creating custom wxpython GUIs.

Also, I am interested in what your overall vision for this project is? Is it mainly to be an alternative to programs like e-sword?

**Comment by t1m0thyj** [comment]
@Correct-Syntax Hi, thanks for reaching out! I'd be happy to have collaborators for this project 🙂 

I've used other Bible programs like e-Sword and theWord.net before, so am kind of familiar with them. My main inspiration for Berean was actually an old app called [BerBible](https://berbible.software.informer.com/2.5/) that I used years ago.

> Do you have plans for custom (and modern) layout and look?

I'm curious what you mean by this, since IMO the wxWidgets/wxPython AUI framework used by Berean is modern and allows for customizable layouts. Although I'm open to other UI ideas, as GUI creation is not my strong suit.

> Also, I am interested in what your overall vision for this project is? Is it mainly to be an alternative to programs like e-sword?

My vision for the project was to have a lightweight app that makes it easy to read and search multiple Bible versions, kind of similar to the feature set of BerBible. After having abandoned the project for a few years, I recently came back to it and made significant updates (migrating from Python 2 to 3, etc). I plan to publish a GitHub release soon, at which point I think my goal may have been mostly reached.

The limited scope of my vision is mainly based on 2 things: (1) This is one of multiple hobby programming projects for me so I don't expect to invest a ton of time in it long term and (2) I haven't found an easy way to incorporate other resources like commentaries, concordances, dictionaries, etc into Berean. The Sword project offers such resources, but PySword only supports Bible modules, and I've tried to build Python bindings to the Sword C++ SDK before but that proved to be a painful and difficult process.

If you have ideas for enhancing Berean and extending its capabilities, I definitely wouldn't discourage you from this 🙂 Even if I don't have time/resources to add them myself, I think collaboration could expand what is possible.

**Comment by Correct-Syntax** [comment]
Hi @t1m0thyj thanks for your response. 

> My main inspiration for Berean was actually an old app called BerBible that I used years ago.

I see the similarities. 😄 

> I'm curious what you mean by this, since IMO the wxWidgets/wxPython AUI framework used by Berean is modern and allows for customizable layouts. Although I'm open to other UI ideas, as GUI creation is not my strong suit.

My idea was mainly to clean up the UI a bit and give it a modern look with different icons and better color consistency. In addition, a possibility is to use custom widgets (i.e non-native widgets) to allow for theming, etc. 

> My vision for the project was to have a lightweight app that makes it easy to read and search multiple Bible versions, kind of similar to the feature set of BerBible.

Okay. That makes sense.

> I haven't found an easy way to incorporate other resources like commentaries, concordances, dictionaries, etc into Berean. The Sword project offers such resources, but PySword only supports Bible modules, and I've tried to build Python bindings to the Sword C++ SDK before but that proved to be a painful and difficult process.

Ah, I see. It would be really great to have concordances, dictionaries, etc as well. It also seems that pysword doesn't look like it's been updated in a while?

I'll see if I can open a PR with what I am thinking (initially) for the UI and you can tell me what you think. 🙂 

Also, I've come across a few bugs which I will likely report as well.
